services:
  db:
    image: mysql:9.2.0-oraclelinux9
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tests
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local
